name: Publish Beta Package to npmjs
on: workflow_dispatch
  
permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CI Git User
        run: |
          git config --global user.name '@jpmorganchase'
          git config --global user.email 'jpmorganchase@users.noreply.github.com'
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@jpmorganchase'
      - run: |
          npm ci
          npm run build
          npm publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_JPMC_PUBLISHER }}
